//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/RehtseStudio/RS_InGameInputMaps/RehtseStudio_InGameInputActionsMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehtseStudio.InGameInputActionsMap
{
    public interface IInputActionCollection2
    {
    }
}